apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:
  name: back-svc              # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: back-svc
spec:
  type: NodePort              # The service will be exposed by opening a Port on each node and proxying it.
  selector:
    app: back-deploy          # The service exposes Pods with label `app=back`
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 31007
      targetPort: 8080